### ISSUE TITLE
Support for proto3?

### ISSUE THREAD

**Issue by carlisia** [ruby-protobuf/protobuf#259]
Hello there,

When I try to compile a [proto3](https://developers.google.com/protocol-buffers/docs/proto3) file, I get this errror:

```Unrecognized syntax identifier "proto3".  This parser only recognizes "proto2".```

I wanted to confirm that this gem does not support proto3, is this the case?

**Comment by abrandoned** [comment]
that is correct, we currently don't have proto3 support

**Comment by carlisia** [comment]
Are there plans to add this support? And thanks.

**Comment by abrandoned** [comment]
@carlisia we do plan on adding the support, currently the timeline is unknown, but we have been working on a new parser that will give us the extensibility to support both versions

**Comment by carlisia** [comment]
@abrandoned thanks for the info.
