### ISSUE TITLE
Ruby protobuf not encode bool type with value = false

### ISSUE THREAD

**Issue by nicolanice** [ruby-protobuf/protobuf#263]
Example:
```ruby
Google::Protobuf::DescriptorPool.generated_pool.build do
   add_message "Test" do
     oneof :value do
       optional :val1, :bool, 1
       optional :val2, :int32, 2
     end
   end
 end

Test = Google::Protobuf::DescriptorPool.generated_pool.lookup("Test").msgclass

t1 = Test.new(val1: true)
t2 = Test.new(val1: false)
Test.decode(Test.encode(t1))  # <Test: val1: true, val2: nil>

Test.decode(Test.encode(t2))  # <Test: val1: nil, val2: nil>

# Encoding
Test.encode(t1)  # "0\x01"
Test.encode(t2)  # ""

Test.decode("0\x00") # # <Test: val1: false, val2: nil>
```

Rails 4.2.3
Ruby 2.2.1p85
google-protobuf (3.0.0.alpha.3.1.pre)
protobuf (~> 3.3.6)
Where the problem ?

**Comment by alexdean** [comment]
You're using [google-protobuf](https://rubygems.org/gems/google-protobuf). That's a different gem from this one. I don't see an issue tracker on that page, so I'm not sure where you should go to ask for help.

**Comment by liveh2o** [comment]
Yeah, as @alexdean states, that's a different gem. Perhaps you'll have some luck in their [support section](https://developers.google.com/protocol-buffers/docs/faq).

I'm going to close this since it doesn't apply to this gem.
