### ISSUE TITLE
Enum_for_tags will implicitly return the first enum when tag is nil

### ISSUE THREAD

**Issue by film42** [ruby-protobuf/protobuf#265]
Right now we call `tag.to_i`, which means if `tag` is nil, then we will always return the first enum, since `nil.to_i` is 0.

**Comment by vintagepenguin** [comment]
@film42 can we close this issue since your PR was merged in?

**Comment by film42** [comment]
Nope. I created this issue because it was a bug pointed out in that PR.

**Comment by evanboho** [comment]
After doing some work on this, I have discovered that this is only a problem if you zero-index your enums. `enum_for_tags` takes a tag as an argument, not an index, so if you do not have a tag of `0`, then this will return nil as expected.

But, I have a PR which fixes it the bug for zero-indexed enums: https://github.com/ruby-protobuf/protobuf/pull/351
