### ISSUE TITLE
behavior of `.new`

### ISSUE THREAD

**Issue by mooreniemi** [ruby-protobuf/protobuf#274]
Very high chance I am Doing It Wrong™ but: I've extended a proto message, and I wanted to understand the behavior of `.new`.

When I use `.all_fields` I see the extended field. So I expected I'd be able to address it directly like `ExtendedThing.new({original_param: "is fine", extended_param: "is never set"})`. But, all I ever see are the original params. In Ruby terms, the receiver has the knowledge of the extensions, but can't actually receive messages to instantiate them.

Is there some way I can use `.new` to set my extensions as well?

Oh and FWIW, I am on Ruby 2.2.2 and the latest release (3.5.5).

**Comment by mooreniemi** [comment]
Ah, apologies, I see though it doesn't _output_ it is still setting it and accessible to me:

```ruby
main » Mason::Edit.new({href: "http", template: FilterViewSubmissions.new({category: "doodle"})})
=> #<Mason::Edit href="http" method=nil title="" encoding="">
main » mason = _
=> #<Mason::Edit href="http" method=nil title="" encoding="">
main » mason.template
=> #<FilterViewSubmissions category="doodle" has_photo="">
main »
```

Closing!

**Comment by mmmries** [comment]
@mooreniemi thanks for taking the time to open a PR. Glad you found the issue on your own in this case, but happy that you would take the time to improve the project if something were wrong.

Feel free to reach out if you encounter other issues in the future.

**Comment by mooreniemi** [comment]
@mmmries Well, while I have you, is the below issue a case of https://github.com/ruby-protobuf/protobuf/pull/70?

I have this in my `.proto`
```proto
message EditViewSubmission {
  // someday gen this from schema?
  optional string category = 1;
  optional string has_photo = 2;
}

extend mason.Edit {
  optional EditViewSubmission template = 199;
}

message CreateViewSubmission {
  // someday gen this from schema?
  optional string category = 1;
  optional string has_photo = 2;
}

extend mason.Create {
  optional CreateViewSubmission template = 199;
}
```
But on compile (`protoc -I ./definitions --ruby_out ./lib/picatrix/generated definitions/*.proto`) I get:

> app.proto:45:33: "template" is already defined.

I would've thought that because CreateViewSubmission and EditViewSubmission are distinct, as are Edit and Create, that they would not conflict. Am I misunderstanding something here, or should I open a bug?

**Comment by mmmries** [comment]
hmmmm, that does seem odd to me. I replicated it locally and that error message of "template" is already defined is actually coming from the `protoc` compiler, not the ruby library.

So I don't think we can work around that on the ruby side, but I could make the protoc library play nice by changing the proto to something like:

```protocol-buffers
package mason;

message EditViewSubmission {
  // someday gen this from schema?
  optional string category = 1;
  optional string has_photo = 2;
}

message CreateViewSubmission {
  // someday gen this from schema?
  optional string category = 1;
  optional string has_photo = 2;
}

message Edit {
  extensions 150 to max;

  extend Edit {
    optional EditViewSubmission template = 199;
  }
}

message Create {
  extensions 150 to max;

  extend Create {
    optional CreateViewSubmission template = 199;
  }
}
```

basically moving the extension to happen inside the message rather than extending it another file. I don't know of  reason why it would be expected to work that way, but I hesitate to call it a bug since I know the team being the `protoc` compiler has a lot of expertise and a lot of time invested into it.

**Comment by mooreniemi** [comment]
Huh, yeah def seems on the protoc side, not this lib's. I'll try some strategies from http://www.indelible.org/ink/protobuf-polymorphism/ or elsewhere and see if I can get it going. Thanks a lot for your assistance!
