### ISSUE TITLE
bool field will return nil when false is setted

### ISSUE THREAD

**Issue by y-hatatani** [ruby-protobuf/protobuf#298]
we get nil, when we accept bool field setted false.

**Comment by y-hatatani** [comment]
this commit may be occured.

https://github.com/ruby-protobuf/protobuf/commit/05aa7756e489e792c7bb0785ef2979931a4879a6

https://github.com/ruby-protobuf/protobuf/blob/master/lib/protobuf/field/base_field.rb#L230

**Comment by film42** [comment]
This has been fixed in `v3.6.6`.
