### ISSUE TITLE
Does this gem support protobuf v3?

### ISSUE THREAD

**Issue by mainameiz** [ruby-protobuf/protobuf#384]
???

**Comment by abrandoned** [comment]
no, not yet

**Comment by film42** [comment]
@mainameiz Interesting. I don't think any of use have tried using protobuf v3 with this gem. That's exciting to hear that it already seems to be working! If we can add tests to assert v3 coverage is :ok_hand: then I think we can start advertising v3 support. Thanks for the insight, @mainameiz !

**Comment by abrandoned** [comment]
@mainameiz @film42 that will be true for all messages that are binary compat between 2 and 3 .... 3 introduces maps and `reserved` keyword and a few other language constructs, the definitions are meant to be backward compat but not forward https://developers.google.com/protocol-buffers/docs/reference/proto3-spec

**Comment by mainameiz** [comment]
Thanks for help
