### ISSUE TITLE
to_json broken as of 0.9.1 since 0.8.0

### ISSUE THREAD

**Issue by taf2** [ruby-protobuf/protobuf#401]
When upgrading google-protobuf ruby library this morning we observed it caused a regression when using google speech to text service.  Objects are now serialized as {} instead of {alternatives: [ {word: 'hello', ... }, {world: 'world', ... }, ... ]

To replicate install google-cloud-speech

transcribe using an operation

get the operation and when it's finished

```
puts operation.response.results.to_json.inspect
```
```
"[{},{},{}]"
```
when using 0.9.1

but when using 0.8.0 gem

```
[{"alternatives"=>[{"transcript"=>"Hello. Hello. Yes, I would like to learn more about Friday.", "confidence"=>0.8977590203285217, "words"=>[{"start_time"=>{"seconds"=>11, "nanos"=>300000000},
```

Seems like a regression in 0.9.1 when converting a protobuf into JSON...

**Comment by film42** [comment]
@taf2 I think you might be looking for https://github.com/protocolbuffers/protobuf/tree/master/ruby ?

**Comment by taf2** [comment]
@film42 maybe?  are you indicating that it's resolved in master?

**Comment by film42** [comment]
This is the “protobuf” library, not “google-protobuf”. Are you using this
one or the official google protobuf ruby lib?

**Comment by taf2** [comment]
@film42 ah ok very sorry!   i saw ruby-protobuf and must have mis-read as google-protobuf   thank you!

**Comment by film42** [comment]
No problem! Sorry I didn’t get back to you sooner!
