### ISSUE TITLE
Message#to_json should convert field names to lowerCamelCase

### ISSUE THREAD

**Issue by aslakhellesoy** [ruby-protobuf/protobuf#408]
According to the [Protobuf 3 language guide](https://developers.google.com/protocol-buffers/docs/proto3#json_options):

> By default proto3 JSON printer should convert the field name to lowerCamelCase and use that as the JSON name.

I know this library isn't currently targetting Proto 3, but is this something you'd be open to a PR for? Backwards compatibility could be maintained by making this an opt-in feature. For example:

```ruby
json = message.to_json(lower_camel_case: true)
```

**Comment by film42** [comment]
Released in `v3.10.3`.
