### ISSUE TITLE
ruby version compatibility

### ISSUE THREAD

**Issue by ThomasSun001** [ruby-protobuf/protobuf#424]
Hi team, I'm currently using ruby 2.4.1, but for ruby-protobuf, it only support 2.5.0, I just noticed from the readme, so is there a way to use ruby version 2.4.1 to install and run ruby-protobuf?? thx!

**Comment by film42** [comment]
The v2.5 is referring to google protobuf, although that is now out of date.

We do test against ruby 2.4 so you should be just fine to use this lib with ruby 2.4.1:

https://github.com/ruby-protobuf/protobuf/blob/03c841be846edd925ca6ac6747eca7ca358bb3c7/.circleci/config.yml#L46
